---
- name: Criando usuário de Automação
  hosts: 192.168.1.203
  tasks:
  - name: Allow 'wheel' group to have passwordless sudo
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^tiadm'
      line: 'tiadm ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'
    become: yes

  - name: Install Repositorios Necessários
    ansible.builtin.apt_repository:
      repo: ppa:ondrej/php


  - name: Update pacotes
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  - name: Upgrade pacotes
    apt: upgrade=dist force_apt_get=yes


  - name: Instalando NGINX e pacotes do PHP
    apt:
      pkg:
      - nginx
      - software-properties-common
      - php7.2-fpm
      - php7.2-common
      - php7.2-gmp
      - php7.2-curl
      - php7.2-intl
      - php7.2-mbstring
      - php7.2-xmlrpc
      - php7.2-mysql
      - php7.2-gd
      - php7.2-imap
      - php7.2-ldap
      - php-cas
      - php7.2-bcmath
      - php7.2-xml
      - php7.2-cli
      - php7.2-zip
      - php7.2-sqlite3